name: Rollback

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Commit SHA to rollback to'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Register rollback task definition
        run: |
          TASK_DEF=$(aws ecs describe-task-definition \
            --task-definition deploy-demo \
            --region ap-southeast-1 \
            --query 'taskDefinition' \
            --output json)

          NEW_TASK_DEF=$(echo $TASK_DEF | jq \
            --arg IMAGE "867344443810.dkr.ecr.ap-southeast-1.amazonaws.com/deploy-demo:${{ github.event.inputs.image_tag }}" \
            '.containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .placementConstraints, .compatibilities, .registeredAt, .registeredBy)')

          aws ecs register-task-definition \
            --region ap-southeast-1 \
            --cli-input-json "$NEW_TASK_DEF"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Update ECS service to rollback revision
        run: |
          REVISION=$(aws ecs describe-task-definition \
            --task-definition deploy-demo \
            --region ap-southeast-1 \
            --query 'taskDefinition.revision' \
            --output text)

          aws ecs update-service \
            --cluster deploy-demo \
            --service deploy-demo-service \
            --task-definition deploy-demo:$REVISION \
            --region ap-southeast-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}